import type { Term } from './types'

/* Seeded sample (~8 core terms). Rendered A–Z. */
export const TERMS: Term[] = [
  {
    term: 'Atonement',
    short: "The reconciling of God and humanity through Christ's death.",
    long: "Atonement refers to how the broken relationship between a holy God and sinful people is repaired. Christianity teaches that Jesus, by his death on the cross, bore the penalty of sin in our place, so that those who trust him are reconciled to God. The word literally captures the idea of being made 'at one' with God again.",
    see_also: ['Grace', 'Justification', 'Gospel'],
  },
  {
    term: 'Covenant',
    short: 'A binding relationship God initiates with his people.',
    long: 'A covenant is a solemn, committed relationship — more than a contract. Throughout Scripture God binds himself to his people by covenant: with Noah, Abraham, Israel through Moses, and finally the “new covenant” in Christ, in which God promises to forgive sins and write his law on human hearts.',
    see_also: ['Grace'],
  },
  {
    term: 'Gospel',
    short: "The 'good news' that God saves sinners through Jesus.",
    long: "'Gospel' means good news. At its heart it is the announcement that Jesus, the Son of God, lived, died for sins, and rose again, so that all who trust him are forgiven and reconciled to God. It is called good news because it is something God has done, received as a gift rather than achieved.",
    see_also: ['Grace', 'Atonement', 'Repentance'],
  },
  {
    term: 'Grace',
    short: 'God’s unearned favor and kindness toward the undeserving.',
    long: 'Grace is God’s free, unmerited goodness — favor no one can earn. Christianity teaches that salvation is by grace: not a wage paid for good behavior but a gift given freely through Jesus Christ, received by faith. Grace also names the ongoing help God gives to live a new life.',
    see_also: ['Gospel', 'Justification', 'Sanctification'],
  },
  {
    term: 'Justification',
    short: 'God declaring a believing sinner right with him.',
    long: 'Justification is a legal picture: God, the righteous Judge, declares a person “not guilty” and counts them righteous — not because of their own works but because of Christ’s righteousness received by faith. It is a status God grants, the beginning of the Christian life rather than a reward at its end.',
    see_also: ['Grace', 'Atonement', 'Sanctification'],
  },
  {
    term: 'Repentance',
    short: 'A turning from sin and back toward God.',
    long: 'Repentance is a change of mind and direction — turning away from sin and self and toward God. It is more than feeling sorry; it is a reorientation of the whole life. In the New Testament, repentance and faith go together as the response to the gospel.',
    see_also: ['Gospel', 'Grace'],
  },
  {
    term: 'Sanctification',
    short: 'The lifelong process of being made holy.',
    long: 'If justification is being declared right with God in an instant, sanctification is the ongoing work of actually becoming like Christ over a lifetime. It is the Holy Spirit gradually transforming a believer’s character, desires, and conduct — a cooperative growth in holiness.',
    see_also: ['Justification', 'Grace'],
  },
  {
    term: 'Trinity',
    short: 'One God eternally existing as Father, Son, and Holy Spirit.',
    long: 'The Trinity is the Christian understanding of God: one Being in three co-equal, co-eternal persons — Father, Son, and Holy Spirit. Not three gods, and not one person in three modes, but one God in three persons. It is confessed in the ancient creeds and drawn from the whole witness of Scripture.',
    see_also: ['Gospel', 'Holy Spirit', 'Incarnation'],
  },
  {
    term: 'Apostle',
    short: 'One “sent out” — especially Jesus’ chosen witnesses.',
    long: 'An apostle is one sent with authority to represent another. In the New Testament it refers especially to the twelve disciples Jesus chose, and to others like Paul, commissioned as eyewitnesses and foundational teachers of the early Church.',
    see_also: ['Church', 'Gospel'],
  },
  {
    term: 'Baptism',
    short: 'The washing that marks entry into the Christian faith.',
    long: 'Baptism is the sign of belonging to Christ and his Church, using water in the name of the Father, Son, and Holy Spirit. Christians differ over its meaning and who should receive it, but nearly all practice it as commanded by Jesus.',
    see_also: ['Church', 'Repentance'],
  },
  {
    term: 'Church',
    short: 'The community of all who belong to Christ.',
    long: 'The Church is not a building but the people of God — everyone united to Christ by faith, worldwide and across history. The New Testament pictures it as Christ’s body, his bride, and a family, gathered to worship, love, and serve.',
    see_also: ['Gospel', 'Baptism', 'Lord’s Supper'],
  },
  {
    term: 'Faith',
    short: 'Trust in God and in what he has promised.',
    long: 'Faith is more than agreeing that something is true; it is trust — resting in God and relying on Jesus for salvation. It is the means by which grace is received, and it shows itself in a life of obedience and love.',
    see_also: ['Grace', 'Gospel', 'Justification'],
  },
  {
    term: 'Heaven',
    short: 'God’s presence, and the eternal home of his people.',
    long: 'Heaven is where God’s presence and rule are fully known. Christian hope is not merely “going to heaven” as disembodied souls, but resurrection life with God in a renewed creation — the new heavens and new earth.',
    see_also: ['Resurrection', 'Kingdom of God'],
  },
  {
    term: 'Hell',
    short: 'Final separation from God for the unrepentant.',
    long: 'Hell is the sober biblical warning of final judgment — being cut off from God’s presence and goodness. Christians hold it seriously and soberly; it is part of why the gospel is such urgent good news.',
    see_also: ['Gospel', 'Repentance'],
  },
  {
    term: 'Holy Spirit',
    short: 'God himself, present and at work in the world and in believers.',
    long: 'The Holy Spirit is the third person of the Trinity — fully God, not merely a force. The Spirit gives new birth, dwells in believers, produces Christlike character, empowers for service, and unites the Church.',
    see_also: ['Trinity', 'Sanctification', 'Church'],
  },
  {
    term: 'Incarnation',
    short: 'God the Son becoming human in Jesus.',
    long: 'The Incarnation is the truth that the eternal Son of God took on human nature and was born as Jesus of Nazareth — fully God and fully man in one person. It is the heart of Christmas and the foundation of salvation.',
    see_also: ['Trinity', 'Gospel', 'Atonement'],
  },
  {
    term: 'Kingdom of God',
    short: 'God’s reign — already begun in Jesus, not yet complete.',
    long: 'The Kingdom of God is God’s saving rule, breaking into the world through Jesus. It is “already” present wherever he is honored, and “not yet” fully realized until he returns to make all things right.',
    see_also: ['Gospel', 'Heaven'],
  },
  {
    term: 'Lord’s Supper',
    short: 'The bread and cup that remember Christ’s death.',
    long: 'Also called Communion or the Eucharist, the Lord’s Supper is the meal Jesus gave his followers — bread and cup recalling his body and blood given for them. Traditions understand his presence differently, but all treat it as sacred.',
    see_also: ['Church', 'Atonement'],
  },
  {
    term: 'Mercy',
    short: 'God’s compassion that withholds deserved judgment.',
    long: 'Mercy is God not giving us the punishment our sin deserves, moved by his compassion. Closely tied to grace, it is shown supremely at the cross — and God calls those who receive mercy to show it to others.',
    see_also: ['Grace', 'Atonement'],
  },
  {
    term: 'Messiah',
    short: 'The promised, anointed deliverer — Jesus the Christ.',
    long: '“Messiah” (Hebrew) and “Christ” (Greek) both mean “anointed one.” The Old Testament looked for an anointed king to save God’s people; Christians confess that Jesus is that promised Messiah.',
    see_also: ['Gospel', 'Covenant'],
  },
  {
    term: 'Providence',
    short: 'God’s wise care and rule over all things.',
    long: 'Providence is the truth that God sustains and governs all that happens, working even hardship toward good purposes for those who love him. It grounds Christian trust and peace amid uncertainty.',
    see_also: ['Grace'],
  },
  {
    term: 'Redemption',
    short: 'Being bought back and set free by Christ.',
    long: 'Redemption pictures rescue at a price — as a slave set free or a debt paid. Christianity teaches that Jesus redeems his people by his death, freeing them from sin’s guilt and power.',
    see_also: ['Atonement', 'Grace', 'Salvation'],
  },
  {
    term: 'Resurrection',
    short: 'Rising bodily from death — Christ’s, and his people’s.',
    long: 'Resurrection is bodily return to life, never to die again. Jesus’ resurrection is the center of the Christian faith and the guarantee that all who belong to him will likewise be raised to eternal life.',
    see_also: ['Gospel', 'Heaven'],
  },
  {
    term: 'Righteousness',
    short: 'Being right with God and doing what is right.',
    long: 'Righteousness means both a right standing before God and right living. Christianity teaches that we cannot achieve it on our own; God credits Christ’s righteousness to those who trust him, then works real change in them.',
    see_also: ['Justification', 'Grace', 'Sanctification'],
  },
  {
    term: 'Salvation',
    short: 'God’s rescue of people from sin and its consequences.',
    long: 'Salvation is the whole of what God does to rescue people — forgiving sin, reconciling them to himself, giving new life, and finally raising them to eternal life. It is God’s work from start to finish, received by faith.',
    see_also: ['Grace', 'Gospel', 'Redemption'],
  },
  {
    term: 'Sin',
    short: 'Falling short of God’s will — in act, word, and heart.',
    long: 'Sin is any failure to love God and others as we should — not only wrong deeds but a deep condition of the human heart. It separates people from God and is the problem the gospel answers.',
    see_also: ['Repentance', 'Grace', 'Atonement'],
  },
  {
    term: 'Adoption',
    short: 'Being received by God as his beloved child.',
    long: 'Adoption is the gracious act by which God brings believers into his own family, giving them the full standing, security, and inheritance of sons and daughters. It is not earned but given through faith in Christ, by whom we call God “Father.”',
    see_also: ['Grace', 'Salvation', 'Justification'],
  },
  {
    term: 'Angel',
    short: 'A spiritual messenger and servant of God.',
    long: 'Angels are created spiritual beings who worship God and carry out his will — announcing his word, protecting his people, and serving his purposes. They are servants of God, never to be worshiped themselves.',
    see_also: ['Heaven', 'Satan'],
  },
  {
    term: 'Ascension',
    short: 'Jesus’ return to heaven after his resurrection.',
    long: 'Forty days after rising, Jesus was taken up into heaven, where he now reigns at the Father’s right hand and intercedes for his people. The Ascension means the risen Christ is Lord over all, and that he will one day return.',
    see_also: ['Resurrection', 'Second Coming', 'Kingdom of God'],
  },
  {
    term: 'Born Again',
    short: 'The new spiritual birth God gives believers.',
    long: 'To be born again (or “regenerated”) is to be given new spiritual life by the Holy Spirit — a fresh heart that trusts and loves God. Jesus taught that this new birth, not mere religion, is how one enters the kingdom of God.',
    see_also: ['Regeneration', 'Holy Spirit', 'Salvation', 'Faith'],
  },
  {
    term: 'Canon',
    short: 'The recognized collection of books in the Bible.',
    long: 'The canon is the list of writings the Church recognizes as Scripture — 66 books in the Protestant Bible. The word means “measuring rod”: these are the books that serve as the standard for Christian faith and life.',
    see_also: ['Scripture'],
  },
  {
    term: 'Conscience',
    short: 'The inner sense of right and wrong.',
    long: 'Conscience is the God-given inner witness that approves what is good and accuses what is wrong. It can be trained by Scripture or dulled by sin, and it points to our accountability before God.',
    see_also: ['Sin', 'Repentance'],
  },
  {
    term: 'The Cross',
    short: 'The place and means of Christ’s saving death.',
    long: 'The cross was a Roman instrument of execution, but in the gospel it becomes the place where Jesus bore the penalty of sin to reconcile people to God. It stands at the center of the Christian faith as both the depth of human sin and the height of God’s love.',
    see_also: ['Atonement', 'Gospel', 'Redemption'],
  },
  {
    term: 'Disciple',
    short: 'A follower and learner of Jesus.',
    long: 'A disciple is a student who follows a teacher to become like him. To be a disciple of Jesus is to trust him, obey his teaching, and be shaped into his likeness — and to help others do the same.',
    see_also: ['Apostle', 'Church', 'Sanctification'],
  },
  {
    term: 'Election',
    short: 'God’s gracious choosing of people for salvation.',
    long: 'Election is the biblical teaching that God, out of grace and not human merit, sets his love on people to save them. Christians differ on exactly how it works alongside human choice, but all agree salvation begins in God’s initiative, not ours.',
    see_also: ['Grace', 'Providence', 'Salvation'],
  },
  {
    term: 'Eternal Life',
    short: 'Unending life in relationship with God.',
    long: 'Eternal life is more than endless existence; it is knowing God and enjoying him forever. It begins now for those who trust Christ and is completed in resurrection and the renewed creation.',
    see_also: ['Salvation', 'Heaven', 'Resurrection'],
  },
  {
    term: 'Evangelism',
    short: 'Sharing the good news of Jesus with others.',
    long: 'Evangelism is telling people the gospel — that Jesus died and rose to save sinners — and inviting them to trust him. Jesus gave his followers the “Great Commission” to make disciples of all nations.',
    see_also: ['Gospel', 'Church', 'Repentance'],
  },
  {
    term: 'Faithfulness',
    short: 'Steadfast, dependable loyalty.',
    long: 'Faithfulness is the quality of being reliable and true — supremely a description of God, who always keeps his promises. It is also the character God grows in his people, who are called to be faithful to him and to one another.',
    see_also: ['Faith', 'Covenant', 'Providence'],
  },
  {
    term: 'The Fall',
    short: 'Humanity’s first sin and its ruinous effects.',
    long: 'The Fall refers to Adam and Eve’s disobedience in the Garden, which brought sin, guilt, and death into the world and fractured humanity’s relationship with God. Everything the gospel addresses flows from this rupture.',
    see_also: ['Sin', 'Original Sin', 'Redemption'],
  },
  {
    term: 'Fellowship',
    short: 'Shared life and communion among believers.',
    long: 'Fellowship is the deep sharing of life that flows from a shared union with Christ — worshiping, encouraging, serving, and bearing one another’s burdens. It reflects the communion believers have with God himself.',
    see_also: ['Church', 'Lord’s Supper'],
  },
  {
    term: 'Flesh',
    short: 'The sinful nature that resists God.',
    long: 'In much of the New Testament, “the flesh” names the fallen human nature — the inner pull toward sin and self rather than God. The Christian life is a Spirit-empowered battle to put the flesh to death and grow in holiness.',
    see_also: ['Sin', 'Sanctification', 'Holy Spirit'],
  },
  {
    term: 'Forgiveness',
    short: 'The release of a debt of sin.',
    long: 'Forgiveness is God’s gracious cancelling of the guilt our sin deserves, made possible through Christ’s death. Having been forgiven so freely, Christians are called to forgive others from the heart.',
    see_also: ['Grace', 'Mercy', 'Atonement'],
  },
  {
    term: 'Fruit of the Spirit',
    short: 'The Christlike character the Spirit grows.',
    long: 'The fruit of the Spirit — love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control — is the character God’s Spirit produces in a believer’s life over time. It is grown, not manufactured, as one walks with God.',
    see_also: ['Holy Spirit', 'Sanctification', 'Love (Agape)'],
  },
  {
    term: 'Glory',
    short: 'The weighty splendor and worth of God.',
    long: 'Glory is the greatness, beauty, and worth of God made visible — his radiant presence and honor. Everything exists for God’s glory, and one day his people will share in it, fully transformed.',
    see_also: ['Worship', 'Heaven'],
  },
  {
    term: 'Hope',
    short: 'Confident expectation of God’s promises.',
    long: 'Biblical hope is not wishful thinking but sure confidence in what God has promised — supremely the resurrection and eternal life. It anchors the soul and sustains believers through suffering.',
    see_also: ['Faith', 'Resurrection', 'Eternal Life'],
  },
  {
    term: 'Idolatry',
    short: 'Worshiping anything in the place of God.',
    long: 'Idolatry is giving to something created the love, trust, or worship that belongs to God alone — whether a carved image or a modern idol like money, success, or self. The Bible treats it as the root of much human sin.',
    see_also: ['Sin', 'Worship'],
  },
  {
    term: 'Image of God',
    short: 'Humanity made to reflect God.',
    long: 'To be made in the image of God (imago Dei) means every human being uniquely reflects God and possesses inherent dignity, worth, and a calling to represent him. Though marred by sin, that image is restored in Christ.',
    see_also: ['Sin', 'Sanctification'],
  },
  {
    term: 'Immanuel',
    short: '“God with us” — a name for Jesus.',
    long: 'Immanuel, meaning “God with us,” is the name prophesied for the Messiah and fulfilled in Jesus. It captures the wonder of the Incarnation: in Christ, God himself came to dwell among his people.',
    see_also: ['Incarnation', 'Messiah'],
  },
  {
    term: 'Judgment',
    short: 'God’s righteous assessment of all people.',
    long: 'Judgment is God’s just evaluation of human life. The Bible speaks of a final Day when all will stand before him; for those in Christ it holds no condemnation, because he has borne their judgment already.',
    see_also: ['Righteousness', 'Hell', 'Second Coming'],
  },
  {
    term: 'Lamb of God',
    short: 'Jesus as the sacrifice for sin.',
    long: 'John the Baptist called Jesus “the Lamb of God, who takes away the sin of the world.” The title connects Jesus to the Passover lamb and the temple sacrifices — the innocent one offered in the place of the guilty.',
    see_also: ['Atonement', 'Passover', 'Gospel'],
  },
  {
    term: 'Law',
    short: 'God’s commands for his people.',
    long: 'The Law is God’s revealed will, summed up in loving God and neighbor. It exposes sin and shows what a good life looks like, yet no one is saved by keeping it — it points beyond itself to the grace of the gospel.',
    see_also: ['Gospel', 'Grace', 'Righteousness'],
  },
  {
    term: 'Love (Agape)',
    short: 'Self-giving love that seeks another’s good.',
    long: 'Agape is the New Testament word for love that gives itself for the good of another, regardless of merit — the love God shows in Christ and calls his people to imitate. It is the greatest mark of a follower of Jesus.',
    see_also: ['Grace', 'Gospel', 'Fruit of the Spirit'],
  },
  {
    term: 'Miracle',
    short: 'A sign of God’s power that points beyond itself.',
    long: 'A miracle is an act of God that goes beyond the ordinary workings of nature, revealing his power and confirming his word. In the Gospels, Jesus’ miracles are “signs” that display who he is and the coming of God’s kingdom.',
    see_also: ['Gospel', 'Kingdom of God'],
  },
  {
    term: 'New Covenant',
    short: 'God’s promise of forgiveness and a changed heart in Christ.',
    long: 'The New Covenant, promised by the prophets and established by Jesus’ death, is God’s pledge to forgive sins and write his law on human hearts by his Spirit. It fulfills and surpasses the covenants that came before.',
    see_also: ['Covenant', 'Gospel', 'Grace'],
  },
  {
    term: 'Original Sin',
    short: 'The sinful condition all people inherit.',
    long: 'Original sin is the teaching that, since the Fall, every person is born with a bent toward sin and apart from God — not merely doing wrong things but sharing a fallen nature. It is why salvation must be a gift of grace.',
    see_also: ['Sin', 'The Fall', 'Grace'],
  },
  {
    term: 'Parable',
    short: 'An earthly story with a spiritual meaning.',
    long: 'A parable is a short, vivid story drawn from everyday life that Jesus used to reveal truth about God and his kingdom — and to challenge the hearer’s heart. They both illumine the receptive and conceal from the hard-hearted.',
    see_also: ['Kingdom of God', 'Gospel'],
  },
  {
    term: 'Passover',
    short: 'Israel’s deliverance feast, fulfilled in Christ.',
    long: 'Passover remembers the night God spared Israel’s firstborn and freed them from Egypt, marked by the blood of a lamb. The New Testament presents Jesus as the true Passover Lamb whose blood brings a greater deliverance from sin and death.',
    see_also: ['Lamb of God', 'Redemption', 'Lord’s Supper'],
  },
  {
    term: 'Peace',
    short: 'Wholeness and reconciliation with God and others.',
    long: 'Biblical peace (Hebrew shalom) is more than the absence of conflict — it is wholeness, flourishing, and right relationship. Through Christ, believers have peace with God, and are called to be peacemakers with others.',
    see_also: ['Reconciliation', 'Gospel', 'Grace'],
  },
  {
    term: 'Pentecost',
    short: 'The outpouring of the Spirit and birth of the Church.',
    long: 'Fifty days after Easter, at the feast of Pentecost, God poured out the Holy Spirit on Jesus’ followers, empowering them to proclaim the gospel. Thousands believed, and the Church was born.',
    see_also: ['Holy Spirit', 'Church'],
  },
  {
    term: 'Prayer',
    short: 'Communicating with God.',
    long: 'Prayer is speaking honestly with God — in praise, thanks, confession, and request — and listening to him. Through Christ, believers come to God as a trusted Father, and are invited to pray about everything.',
    see_also: ['Worship', 'Faith'],
  },
  {
    term: 'Prophet',
    short: 'One who speaks God’s word to his people.',
    long: 'A prophet is a person God appoints to speak his message — calling people back to faithfulness, warning of judgment, and pointing to the hope of the Messiah. Their words, recorded in Scripture, still speak today.',
    see_also: ['Scripture', 'Messiah'],
  },
  {
    term: 'Propitiation',
    short: 'The turning away of God’s wrath by a sacrifice.',
    long: 'Propitiation means the satisfying of God’s just wrath against sin through a sacrifice. The New Testament teaches that Jesus is the propitiation for sin — bearing God’s judgment so that mercy could flow to sinners.',
    see_also: ['Atonement', 'Wrath of God', 'Mercy'],
  },
  {
    term: 'Reconciliation',
    short: 'A broken relationship with God restored.',
    long: 'Reconciliation is the ending of hostility and the restoring of friendship between God and sinners through Christ. Those reconciled to God are then given a “ministry of reconciliation” toward others.',
    see_also: ['Atonement', 'Peace', 'Redemption'],
  },
  {
    term: 'Sabbath',
    short: 'The God-given day of rest and worship.',
    long: 'The Sabbath is the weekly day of rest God built into creation and commanded Israel to keep — a time to cease from work, worship, and trust God’s provision. Christians see its rest ultimately fulfilled in Christ.',
    see_also: ['Law', 'Worship'],
  },
  {
    term: 'Saint',
    short: 'Anyone set apart as God’s holy people.',
    long: 'In the Bible a “saint” is not a spiritual elite but any believer — someone set apart by God and made holy in Christ. All Christians are called saints, and are called to live like it.',
    see_also: ['Sanctification', 'Church'],
  },
  {
    term: 'Satan',
    short: 'The adversary who opposes God and tempts people.',
    long: 'Satan (“the accuser”) is a fallen spiritual being who opposes God, accuses believers, and tempts people to sin. He is real but not God’s equal — a defeated enemy whose end is certain because of the cross.',
    see_also: ['Sin', 'Temptation', 'Angel'],
  },
  {
    term: 'Savior',
    short: 'The one who rescues — Jesus.',
    long: 'A savior is one who delivers from danger or ruin. The Bible declares Jesus the Savior of the world, who rescues people not from earthly trouble merely but from sin, death, and judgment.',
    see_also: ['Salvation', 'Gospel', 'Messiah'],
  },
  {
    term: 'Scripture',
    short: 'The written Word of God.',
    long: 'Scripture is the collection of writings Christians receive as the inspired, authoritative Word of God — the Old and New Testaments. It is the trustworthy rule for faith and life, and it points throughout to Christ.',
    see_also: ['Canon', 'Gospel'],
  },
  {
    term: 'Second Coming',
    short: 'The future return of Jesus in glory.',
    long: 'The Second Coming is the promised return of Jesus to judge the world, raise the dead, and make all things new. Christians differ on the details but hold together the sure hope that Christ will come again.',
    see_also: ['Resurrection', 'Judgment', 'Kingdom of God'],
  },
  {
    term: 'Sovereignty of God',
    short: 'God’s supreme rule over all things.',
    long: 'The sovereignty of God is his complete authority and control over all creation and history. Nothing lies outside his rule, which means his purposes cannot be thwarted and his people can trust him in everything.',
    see_also: ['Providence', 'Election'],
  },
  {
    term: 'Temptation',
    short: 'Enticement to turn from God into sin.',
    long: 'Temptation is the pull toward sin, whether from within, the world, or the devil. It is not itself sin — Jesus was tempted yet never sinned — and God provides a way to endure it.',
    see_also: ['Sin', 'Satan'],
  },
  {
    term: 'Wisdom',
    short: 'Skill in living well before God.',
    long: 'Wisdom in the Bible is not mere cleverness but the God-given skill of living rightly in his world. It begins with the fear of the LORD and is embodied perfectly in Christ, “in whom are hidden all the treasures of wisdom.”',
    see_also: ['Righteousness', 'Providence'],
  },
  {
    term: 'Worship',
    short: 'Honoring God for who he is and what he has done.',
    long: 'Worship is ascribing to God the worth he is due — in praise, prayer, and a life laid before him. It is not confined to a service; all of life can be offered to God as worship.',
    see_also: ['Glory', 'Prayer'],
  },
  {
    term: 'Wrath of God',
    short: 'God’s settled, righteous opposition to sin.',
    long: 'The wrath of God is not petty anger but his holy, just response to evil. The gospel’s good news is that at the cross Jesus bore that wrath in the place of sinners, so that those who trust him need never face it.',
    see_also: ['Propitiation', 'Judgment', 'Sin'],
  },
  {
    term: 'Regeneration',
    short: 'The Spirit’s work of giving new spiritual life — the new birth.',
    long: 'Regeneration is the inward act by which the Holy Spirit imparts new spiritual life to someone spiritually dead in sin, giving a new heart that turns to God in faith. It is the “new birth” Jesus spoke of — entirely God’s work, and the beginning of the Christian life.',
    see_also: ['Born Again', 'Holy Spirit', 'Salvation'],
  },
]
