/** The New City Catechism — 52 questions and answers (adult wording),
 *  organized in three parts. A modern, broadly evangelical catechism
 *  (The Gospel Coalition & Redeemer, 2017), drawing on the Reformation
 *  catechisms (Calvin's, Heidelberg, Westminster). Each entry carries the
 *  catechism's own Scripture reference, linked to the ESV reader. */
export interface CatechismQA {
  n: number
  part: 1 | 2 | 3
  question: string
  answer: string
  ref: string
}

export const CATECHISM_TITLE = 'New City Catechism'

export const CATECHISM_INTRO =
  'A catechism is a set of questions and answers used for centuries to teach the core of the Christian faith. The New City Catechism is a modern one — 52 questions, one for each week of the year — that gathers up the historic Reformation catechisms in plainer language.'

export const CATECHISM_ATTRIBUTION =
  'The New City Catechism © 2017 by The Gospel Coalition, Inc. and Redeemer Presbyterian Church, used under a Creative Commons Attribution licence (CC BY 4.0).'

export const CATECHISM_PARTS: Record<1 | 2 | 3, string> = {
  1: 'Part 1 · God, Creation & Fall, the Law',
  2: 'Part 2 · Christ, Redemption, Grace',
  3: 'Part 3 · Spirit, Restoration, Growing in Grace',
}

export const CATECHISM: CatechismQA[] = [
  { n: 1, part: 1, question: 'What is our only hope in life and death?', answer: 'That we are not our own but belong, body and soul, both in life and death, to God and to our Savior Jesus Christ.', ref: 'Romans 14:7–8' },
  { n: 2, part: 1, question: 'What is God?', answer: 'God is the creator and sustainer of everyone and everything. He is eternal, infinite, and unchangeable in his power and perfection, goodness and glory, wisdom, justice, and truth. Nothing happens except through him and by his will.', ref: 'Psalm 86:8–10' },
  { n: 3, part: 1, question: 'How many persons are there in God?', answer: 'There are three persons in the one true and living God: the Father, the Son, and the Holy Spirit. They are the same in substance, equal in power and glory.', ref: '2 Corinthians 13:14' },
  { n: 4, part: 1, question: 'How and why did God create us?', answer: 'God created us male and female in his own image to know him, love him, live with him, and glorify him. And it is right that we who were created by God should live to his glory.', ref: 'Genesis 1:27' },
  { n: 5, part: 1, question: 'What else did God create?', answer: 'God created all things by his powerful Word, and all his creation was very good; everything flourished under his loving rule.', ref: 'Genesis 1:31' },
  { n: 6, part: 1, question: 'How can we glorify God?', answer: 'We glorify God by enjoying him, loving him, trusting him, and by obeying his will, commands, and law.', ref: 'Deuteronomy 11:1' },
  { n: 7, part: 1, question: 'What does the law of God require?', answer: 'Personal, perfect, and perpetual obedience; that we love God with all our heart, soul, mind, and strength; and love our neighbor as ourselves. What God forbids should never be done and what God commands should always be done.', ref: 'Matthew 22:37–40' },
  { n: 8, part: 1, question: 'What is the law of God stated in the Ten Commandments?', answer: 'You shall have no other gods before me. You shall not make for yourself an idol. You shall not misuse the name of the Lord your God. Remember the Sabbath day by keeping it holy. Honor your father and mother. You shall not murder. You shall not commit adultery. You shall not steal. You shall not give false testimony. You shall not covet.', ref: 'Exodus 20:1–17' },
  { n: 9, part: 1, question: 'What does God require in the first, second, and third commandments?', answer: 'First, that we know and trust God as the only true and living God. Second, that we avoid all idolatry and do not worship God improperly. Third, that we treat God’s name with fear and reverence, honoring also his Word and works.', ref: 'Deuteronomy 6:13–14' },
  { n: 10, part: 1, question: 'What does God require in the fourth and fifth commandments?', answer: 'Fourth, that on the Sabbath day we rest from our labor and worship God, so that the kingdom of Christ may advance in the world. Fifth, that we love and honor our father and our mother, submitting to their godly discipline and direction.', ref: 'Leviticus 19:3' },
  { n: 11, part: 1, question: 'What does God require in the sixth, seventh, and eighth commandments?', answer: 'Sixth, that we do not hurt, or hate, or be hostile to our neighbor, but be patient and peaceful, pursuing even our enemies with love. Seventh, that we abstain from sexual immorality and live purely and faithfully, whether in marriage or in single life, avoiding all impure actions, looks, words, thoughts, or desires, and whatever might lead to them. Eighth, that we do not take without permission that which belongs to someone else, nor withhold any good from someone we might benefit.', ref: 'Romans 13:9' },
  { n: 12, part: 1, question: 'What does God require in the ninth and tenth commandments?', answer: 'Ninth, that we do not lie or deceive, but speak the truth in love. Tenth, that we are content, not envying anyone or resenting what God has given them or us.', ref: 'James 2:8' },
  { n: 13, part: 1, question: 'Can anyone keep the law of God perfectly?', answer: 'Since the fall, no mere human has been able to keep the law of God perfectly, but consistently breaks it in thought, word, and deed.', ref: 'Romans 3:10–12' },
  { n: 14, part: 1, question: 'Did God create us unable to keep his law?', answer: 'No, but because of the disobedience of our first parents, Adam and Eve, all of creation is fallen; we are all born in sin and guilt, corrupt in our nature, and unable to keep God’s law.', ref: 'Romans 5:12' },
  { n: 15, part: 1, question: 'Since no one can keep the law, what is its purpose?', answer: 'That we may know the holy nature and will of God, and the sinful nature and disobedience of our hearts; and thus our need of a Savior. The law also teaches and exhorts us to live a life worthy of our Savior.', ref: 'Romans 3:20' },
  { n: 16, part: 1, question: 'What is sin?', answer: 'Sin is rejecting or ignoring God in the world he created, rebelling against him by living without reference to him, not being or doing what he requires in his law — resulting in our death and the disintegration of all creation.', ref: '1 John 3:4' },
  { n: 17, part: 1, question: 'What is idolatry?', answer: 'Idolatry is trusting in created things rather than the Creator for our hope and happiness, significance and security.', ref: 'Romans 1:21, 25' },
  { n: 18, part: 1, question: 'Will God allow our disobedience and idolatry to go unpunished?', answer: 'No, every sin is against the sovereignty, holiness, and goodness of God, and against his righteous law, and God is righteously angry with our sins and will punish them in his just judgment both in this life, and in the life to come.', ref: 'Ephesians 5:5–6' },
  { n: 19, part: 1, question: 'Is there any way to escape punishment and be brought back into God’s favor?', answer: 'Yes, to satisfy his justice, God himself, out of mere mercy, reconciles us to himself and delivers us from sin and from the punishment for sin, by a Redeemer.', ref: 'Isaiah 53:10–11' },
  { n: 20, part: 1, question: 'Who is the Redeemer?', answer: 'The only Redeemer is the Lord Jesus Christ, the eternal Son of God, in whom God became man and bore the penalty for sin himself.', ref: '1 Timothy 2:5' },
  { n: 21, part: 2, question: 'What sort of Redeemer is needed to bring us back to God?', answer: 'One who is truly human and also truly God.', ref: 'Isaiah 9:6' },
  { n: 22, part: 2, question: 'Why must the Redeemer be truly human?', answer: 'That in human nature he might on our behalf perfectly obey the whole law and suffer the punishment for human sin; and also that he might sympathize with our weaknesses.', ref: 'Hebrews 2:17' },
  { n: 23, part: 2, question: 'Why must the Redeemer be truly God?', answer: 'That because of his divine nature his obedience and suffering would be perfect and effective; and also that he would be able to bear the righteous anger of God against sin and yet overcome death.', ref: 'Acts 2:24' },
  { n: 24, part: 2, question: 'Why was it necessary for Christ, the Redeemer, to die?', answer: 'Since death is the punishment for sin, Christ died willingly in our place to deliver us from the power and penalty of sin and bring us back to God. By his substitutionary atoning death alone are we redeemed.', ref: 'Colossians 1:21–22' },
  { n: 25, part: 2, question: 'Does Christ’s death mean all our sins can be forgiven?', answer: 'Yes, because Christ’s death on the cross fully paid the penalty for our sin, God graciously imputes Christ’s righteousness to us as if it were our own and will remember our sins no more.', ref: '2 Corinthians 5:21' },
  { n: 26, part: 2, question: 'What else does Christ’s death redeem?', answer: 'Christ’s death is the beginning of the redemption and renewal of every part of fallen creation, as he powerfully directs all things for his own glory and creation’s good.', ref: 'Colossians 1:19–20' },
  { n: 27, part: 2, question: 'Are all people, just as they were lost through Adam, saved through Christ?', answer: 'No, only those who are elected by God and united to Christ by faith. Nevertheless God in his mercy demonstrates common grace even to those who are not elect, by restraining the effects of sin and enabling works of culture for human well-being.', ref: 'Romans 5:17' },
  { n: 28, part: 2, question: 'What happens after death to those not united to Christ by faith?', answer: 'At the day of judgment they will receive the fearful but just sentence of condemnation pronounced against them. They will be cast out from the favorable presence of God, into hell, to be justly and grievously punished, forever.', ref: 'John 3:16–18, 36' },
  { n: 29, part: 2, question: 'How can we be saved?', answer: 'Only by faith in Jesus Christ and in his substitutionary atoning death on the cross. So even though we are guilty of having disobeyed God and are still inclined to all evil, nevertheless, God, without any merit of our own but only by pure grace, imputes to us the perfect righteousness of Christ when we repent and believe in him.', ref: 'Ephesians 2:8–9' },
  { n: 30, part: 2, question: 'What is faith in Jesus Christ?', answer: 'Faith in Jesus Christ is acknowledging the truth of everything that God has revealed in his Word, trusting in him, and also receiving and resting on him alone for salvation as he is offered to us in the gospel.', ref: 'Galatians 2:20' },
  { n: 31, part: 2, question: 'What do we believe by true faith?', answer: 'Everything taught to us in the gospel. The Apostles’ Creed expresses what we believe in these words: We believe in God the Father Almighty, Maker of heaven and earth; and in Jesus Christ his only Son our Lord … and in the Holy Spirit, the holy catholic church, the communion of saints, the forgiveness of sins, the resurrection of the body, and the life everlasting.', ref: '1 Corinthians 15:3–4' },
  { n: 32, part: 2, question: 'What do justification and sanctification mean?', answer: 'Justification means our declared righteousness before God, made possible by Christ’s death and resurrection for us. Sanctification means our gradual, growing righteousness, made possible by the Spirit’s work in us.', ref: '1 Peter 1:1–2' },
  { n: 33, part: 2, question: 'Should those who have faith in Christ seek their salvation through their own works, or anywhere else?', answer: 'No, they should not, as everything necessary to salvation is found in Christ. To seek salvation through good works is a denial that Christ is the only Redeemer and Savior.', ref: 'Galatians 2:16' },
  { n: 34, part: 2, question: 'Since we are redeemed by grace alone, through Christ alone, must we still do good works and obey God’s Word?', answer: 'Yes, because Christ, having redeemed us by his blood, also renews us by his Spirit; so that our lives may show love and gratitude to God; and so that we may be assured of our faith by the fruits, and by our godly lives win our neighbors to Christ.', ref: 'Ephesians 2:10' },
  { n: 35, part: 2, question: 'Since we are redeemed by grace alone, through Christ alone, can we lose our salvation?', answer: 'No, we cannot lose our salvation, since the love God has for us in Christ is eternal, and those whom he has chosen he will keep. And that we may know we are secure, God graciously grants us assurance of salvation through the Spirit and the fruit of the Spirit in our lives.', ref: 'John 10:27–29' },
  { n: 36, part: 3, question: 'What do we believe about the Holy Spirit?', answer: 'That he is God, coeternal with the Father and the Son, and that God grants him irrevocably to all who believe.', ref: 'John 14:16–17' },
  { n: 37, part: 3, question: 'How does the Holy Spirit help us?', answer: 'The Holy Spirit convicts us of our sin, comforts us, guides us, gives us spiritual gifts and the desire to obey God; and he enables us to pray and to understand God’s Word.', ref: '1 Corinthians 2:12' },
  { n: 38, part: 3, question: 'What is prayer?', answer: 'Prayer is pouring out our hearts to God in praise, petition, confession of sin, and thanksgiving.', ref: 'Psalm 62:8' },
  { n: 39, part: 3, question: 'With what attitude should we pray?', answer: 'With love, perseverance, and gratefulness; in humble submission to God’s will, knowing that, for the sake of Christ, he always hears our prayers.', ref: '1 John 5:14' },
  { n: 40, part: 3, question: 'What should we pray?', answer: 'The whole Word of God directs and inspires us in what we should pray, including the prayer Jesus himself taught us.', ref: 'Matthew 6:9–13' },
  { n: 41, part: 3, question: 'What is the Lord’s Prayer?', answer: 'Our Father in heaven, hallowed be your name. Your kingdom come, your will be done, on earth as it is in heaven. Give us this day our daily bread, and forgive us our debts, as we also have forgiven our debtors. And lead us not into temptation, but deliver us from evil. For yours is the kingdom and the power and the glory, forever. Amen.', ref: 'Matthew 6:9–13' },
  { n: 42, part: 3, question: 'How is the Word of God to be read and heard?', answer: 'With diligence, preparation, and prayer; so that we may accept it with faith, store it in our hearts, and practice it in our lives.', ref: '2 Timothy 3:16–17' },
  { n: 43, part: 3, question: 'What are the sacraments or ordinances?', answer: 'The sacraments or ordinances given by God and instituted by Christ, namely baptism and the Lord’s Supper, are visible signs and seals that we are bound together as a community of faith by his death and resurrection. By our use of them the Holy Spirit more fully declares and seals the promises of the gospel to us.', ref: 'Romans 4:11' },
  { n: 44, part: 3, question: 'What is baptism?', answer: 'Baptism is the washing with water in the name of the Father, and of the Son, and of the Holy Spirit. It signifies and seals our adoption into Christ, our cleansing from sin, and our commitment to belong to the Lord and to his church.', ref: 'Matthew 28:19' },
  { n: 45, part: 3, question: 'Is baptism with water the washing away of sin itself?', answer: 'No, only the blood of Christ and the renewal of the Holy Spirit can cleanse us from sin.', ref: '1 Peter 3:21' },
  { n: 46, part: 3, question: 'What is the Lord’s Supper?', answer: 'Christ commanded all Christians to eat bread and to drink from the cup in thankful remembrance of him and his death. The Lord’s Supper is a celebration of the presence of God in our midst; bringing us into communion with God and with one another; feeding and nourishing our souls. It also anticipates the day when we will eat and drink with Christ in his Father’s kingdom.', ref: '1 Corinthians 11:23–26' },
  { n: 47, part: 3, question: 'Does the Lord’s Supper add anything to Christ’s atoning work?', answer: 'No, Christ died once for all. The Lord’s Supper is a covenant meal celebrating Christ’s atoning work; as it is also a means of strengthening our faith as we look to him, and a foretaste of the future feast. But those who take part with unrepentant hearts eat and drink judgment on themselves.', ref: '1 Corinthians 11:28–29' },
  { n: 48, part: 3, question: 'What is the church?', answer: 'God chooses and preserves for himself a community elected for eternal life and united by faith, who love, follow, learn from, and worship God together. God sends out this community to proclaim the gospel and prefigure Christ’s kingdom by the quality of their life together and their love for one another.', ref: 'Ephesians 4:11–13' },
  { n: 49, part: 3, question: 'Where is Christ now?', answer: 'Christ rose bodily from the grave on the third day, victorious over death; and is seated at the right hand of the Father, ruling his kingdom and interceding for us, until he returns to judge and renew the whole world.', ref: 'Ephesians 1:20–21' },
  { n: 50, part: 3, question: 'What does Christ’s resurrection mean for us?', answer: 'Christ triumphed over sin and death by being physically resurrected, so that all who trust in him are raised to new life in this world and to everlasting life in the world to come. Just as we will one day be resurrected, so this world will one day be restored. But those who do not trust in Christ will be raised to everlasting death.', ref: '1 Corinthians 15:20–22' },
  { n: 51, part: 3, question: 'Of what advantage to us is Christ’s ascension?', answer: 'Christ physically ascended on our behalf, just as he came down to earth physically for our sake, and he is now advocating for us in the presence of his Father, preparing a place for us, and also sends us his Spirit.', ref: 'Romans 8:34' },
  { n: 52, part: 3, question: 'What hope does everlasting life hold for us?', answer: 'It reminds us that this present fallen world is not all there is; soon we will live with and enjoy God forever in the new city, in the new heaven and the new earth, where we will be fully and forever freed from all sin and will inhabit renewed, resurrection bodies in a renewed, restored creation.', ref: 'Revelation 21:1–4' },
]
